import config from '../../config';
import { TStudent } from '../student/student.interface';
import { Student } from '../student/student.model';
import { TUser } from './user.interface';
import { User } from './user.model';

const createStudentInDB = async (password: string, studentData: TStudent) => {
  // const student = new Student(studentData);
  // if (await student.isStudentExit(student.id)) {
  //   throw new Error('you are exsisting student.');
  // }
  //   if password is not given use default password

  const userData: Partial<TUser> = {};

  if (!password) {
    userData.password = config.default_password as string;
  } else {
    userData.password = password;
  }
  // set student role
  userData.role = 'student';
  // as id will be generated by admin/client so we manually set _id for student for referencing
  userData.id = '2030100001';
  // 1.create a user
  const newUser = await User.create(userData);
  //   2.now on the basis of user we will create student_id,and userId for embeded and references
  if (Object.keys(newUser).length) {
    studentData.id = newUser.id;
    studentData.user = newUser._id;

    const newStudent = await Student.create(studentData);
    return newStudent;
  }
};

export const UserService = {
  createStudentInDB,
};
